### PR TITLE
feat: fix travis ci after rename FTAllReduceStatus

### PR DESCRIPTION
**Pull request by zw0610**
**What this PR does / why we need it**:

After the travis ci is re-configured, this pr address issues occur after `FTAllReduceStatus` is renamed to `FTCollectiveStatus`

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @terrytangyuan 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zw0610** [comment]
@terrytangyuan It seems the issue is fixed.

**Comment by terrytangyuan** [comment]
Okay but Travis build still failed

**Comment by zw0610** [comment]
> Okay but Travis build still failed

I figured out the reason and please take a look.

**Pull request merged**
