### PR TITLE
feat: add docs and readme

### LINKED ISSUE #9: Provide design doc
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

**What you expected to happen**:

We need a (set of) design doc(s) to show how the ftlib is supposed to work, in which way both the contributors and us will have a clear mind to this lib.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by zw0610**
**What this PR does / why we need it**:

Adding design doc as well as readme and license.

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #9 

Reference to #

**Special notes for your reviewer**:

/cc @terrytangyuan @gaocegege @pendoragon @ddysher 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ddysher** [comment]
There's nothing in the commit, which is probably caused by opensourcing the repository.

**Comment by ddysher** [comment]
BTW, we should include a license file, ref https://github.com/caicloud/cyclone/blob/master/LICENSE

**Comment by zw0610** [comment]
> There's nothing in the commit, which is probably caused by opensourcing the repository.

Yes, I re-forked the repo and it looks working. I'll check with @bbbmj  to make sure the `needs-rebase` tag removed.

**Pull request closed without merging**
