### PR TITLE
Add script to setup k8s environment on Travis CI

### PR DESCRIPTION
**Pull request by terrytangyuan**
Part of #17. The setup is borrowed from ElasticDL. We can add others like dockerfile and k8s yaml later.

### CODE REVIEW

**Comment by gaocegege** [comment]
@terrytangyuan Thanks, should we enable the project build in Travis first then merge it?

**Comment by terrytangyuan** [comment]
@gaocegege I think it’s already enabled by @ddysher. You should be able to see the build now.

**Comment by gaocegege** [comment]
Gotcha.

/lgtm
/approve

**Pull request merged**
